pygments: true
paginate: 9
paginate_path: "/blog/page:num/"
future: true

defaults:
  -
    scope:
      path: ""
    values:
      layout: "page"
  -
    scope:
      path: "_posts"
      type: "post"
    values:
      layout: "post"

