---
title: Haiy.Github.Io
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
pygments: true
paginate: 9
paginate_path: "/blog/page:num/"
future: true
highlighter: rouge
tags:
- jekyll
- code
